joinrpg/joinrpg-net

- JoinRpg.CommonUI.Models/CommentExtraAction.cs
> Fix encoding

- JoinRpg.Dal.Impl/Repositories/ProjectRepository.cs
- JoinRpg.Data.Interfaces/IProjectRepository.cs
- Joinrpg/App_Code/MvcHelpers.cs
- Joinrpg/App_Start/RouteConfig.cs
- Joinrpg/Controllers/CharacterController.cs
- Joinrpg/Controllers/GameFieldController.cs
- Joinrpg/Controllers/GameGroupsController.cs
- Joinrpg/Controllers/PlotController.cs
- Joinrpg/Helpers/CharacterAndGroupPrefixer.cs
- Joinrpg/Helpers/MagicControlHelper.cs
- Joinrpg/JoinRpg.Web.csproj
- Joinrpg/Models/CharacterGroupListViewModel.cs
- Joinrpg/Models/CharacterViewModels.cs
- Joinrpg/Models/GameFieldViewModel.cs
- Joinrpg/Models/GameObjectViewModelBase.cs
- Joinrpg/Models/IProjectIdAware.cs
- Joinrpg/Models/Plot/AddPlotElementViewModel.cs
- Joinrpg/Models/Plot/EditPlotFolderViewModel.cs
- Joinrpg/Scripts/multicontrol.js
> Supercontrol another portion of fixes

- JoinRpg.Domain/ClaimProblemFilters/FinanceProblemsFilter.cs
- JoinRpg.Domain/ClaimProblemFilters/NotAnsweredClaim.cs
> Small fixes for problems

- Joinrpg/Controllers/Common/ControllerGameBase.cs
- Joinrpg/Models/MasterMenuViewModel.cs
- Joinrpg/Views/Shared/_PlayerMenuPartial.cshtml
> Show big groups in player's menu

- JoinRpg.Domain/ProjectEntityExtensions.cs
- Joinrpg/Controllers/ClaimListController.cs
- Joinrpg/Controllers/GameGroupsController.cs
- Joinrpg/Views/Shared/EditorTemplates/SubscribeSettingsViewModel.cshtml
> gSmall fixes 2013 2

- Joinrpg/Controllers/FinancesController.cs
- Joinrpg/Models/FinanceModels.cs
- Joinrpg/Models/IOperationsAwareView.cs
- Joinrpg/Views/Finances/Operations.cshtml
> Unbroke finance lists

- Joinrpg/Controllers/ClaimController.cs
- Joinrpg/Models/CommentModels.cs
- Joinrpg/Views/Claim/Edit.cshtml
> Force order for comments

- Joinrpg/Content/multicontrol.css
- Joinrpg/Scripts/multicontrol.js
> Update supercontrol to next version

- Joinrpg/Controllers/CharacterController.cs
- Joinrpg/Controllers/ClaimController.cs
- Joinrpg/Controllers/GameGroupsController.cs
- Joinrpg/Models/CharacterDetailsViewModel.cs
- Joinrpg/Models/CharacterListItemViewModel.cs
- Joinrpg/Models/Plot/PlotElementViewModel.cs
- Joinrpg/Views/CharacterList/Index.cshtml
- Joinrpg/Views/Shared/_PlotForCharacterPartial.cshtml
fixes #149 fixes #148 fixes #87
> Fix release6 bugs

- JoinRpg.Domain/CharacterFields/FieldWithValue.cs
- JoinRpg.Helpers.Web.Test/JoinRpg.Helpers.Web.Test.csproj
- JoinRpg.Helpers.Web.Test/Properties/AssemblyInfo.cs
- JoinRpg.Helpers.Web.Test/TestIntListCompression.cs
- JoinRpg.Helpers.Web/IdListUrlExtensions.cs
- Joinrpg.sln
- Joinrpg/Controllers/Common/PrintController.cs
- Joinrpg/Controllers/MassMailController.cs
- Joinrpg/Views/Shared/_ListOperationsDropdown.cshtml
> Compress long lists in url

- JoinRpg.DataModel/User.cs
- JoinRpg.Services.Export/BackEnds/ClosedXmlExcelBackend.cs
- JoinRpg.Services.Export/Internal/Cell.cs
- Joinrpg/Helpers/CustomExporter.cs
- Joinrpg/Views/Manage/SetupProfile.cshtml
- Joinrpg/Views/Shared/DisplayTemplates/CharacterParentGroupsViewModel.cshtml
fixes #113 fixes #158 fixes #157b
> Small fixes

- JoinRpg.Domain/CharacterProblemFilters/BrokenCharactersFilter.cs
- JoinRpg.Domain/FieldExtensions.cs
- JoinRpg.Domain/JoinRpg.Domain.csproj
- JoinRpg.Domain/ProblemExtensions.cs
- JoinRpg.Services.Impl/ClaimServiceImpl.cs
- JoinRpg.Services.Impl/FieldSaveHelper.cs
- Joinrpg/Controllers/CharacterListController.cs
- Joinrpg/Models/ProblemViewModel.cs
- Joinrpg/Views/Shared/_MasterMenuPartial.cshtml
fixes #183 and some bugs about assigning special groups
> Broken characters2

- JoinRpg.Dal.Impl/Repositories/ClaimsRepositoryImpl.cs
- JoinRpg.Data.Interfaces/IClaimsRepository.cs
- JoinRpg.DataModel/CharacterGroup.cs
- JoinRpg.DataModel/IntList.cs
- JoinRpg.DataModel/JoinRpg.DataModel.csproj
- JoinRpg.Helpers/StaticStringHelpers.cs
- Joinrpg/Controllers/ClaimListController.cs
- Joinrpg/Controllers/GameController.cs
- Joinrpg/Helpers/ModelStateExtensions.cs
- Joinrpg/Views/Finances/Operations.cshtml
- Joinrpg/Views/Shared/_MasterMenuPartial.cshtml
fixes #197 fixes #196 fixes #61
> Fix a lot of bugs

- JoinRpg.Domain/ProjectEntityExtensions.cs
- Joinrpg/Controllers/CharacterController.cs
- Joinrpg/Views/Plot/Edit.cshtml
- Joinrpg/Views/Plot/EditElementPartial.cshtml
- Joinrpg/Views/Plot/Index.cshtml
- Joinrpg/Views/Shared/DisplayTemplates/PlotFolderListItemViewModel.cshtml
> Hide unready elements in plots publish

- JoinRpg.Domain/Exceptions.cs
- JoinRpg.Domain/ProjectEntityExtensions.cs
- JoinRpg.Services.Impl/ProjectService.cs
- JoinRpg.Services.Interfaces/IProjectService.cs
- Joinrpg/Controllers/CharacterController.cs
- Joinrpg/Controllers/ClaimController.cs
- Joinrpg/Controllers/GameFieldController.cs
- Joinrpg/Controllers/GameGroupsController.cs
- Joinrpg/Controllers/PlotController.cs
- Joinrpg/Models/Characters/CharacterGroupListViewModel.cs
- Joinrpg/Models/Characters/CharacterListItemViewModel.cs
- Joinrpg/Models/Characters/CharacterViewModel.cs
- Joinrpg/Models/Characters/CharacterViewModels.cs
- Joinrpg/Models/ClaimViewModel.cs
- Joinrpg/Models/CustomFieldsViewModels.cs
- Joinrpg/Models/GameFieldViewModel.cs
- Joinrpg/Models/Plot/EditPlotFolderViewModel.cs
- Joinrpg/Models/Plot/PlotElementViewModel.cs
- Joinrpg/Models/Plot/PlotFolderListViewModel.cs
- Joinrpg/Views/Character/Create.cshtml
- Joinrpg/Views/Character/Edit.cshtml
- Joinrpg/Views/Claim/Edit.cshtml
- Joinrpg/Views/GameGroups/_CharacterPartial.cshtml
- Joinrpg/Views/Plot/Edit.cshtml
- Joinrpg/Views/Plot/EditElementPartial.cshtml
- Joinrpg/Views/Plot/ShowElementPartial.cshtml
- Joinrpg/Views/Shared/CharacterNavigation.cshtml
> Prevent editing

- JoinRpg.Domain/ClaimSourceExtensions.cs
- JoinRpg.Domain/Exceptions.cs
- JoinRpg.Services.Impl/ClaimServiceImpl.cs
- JoinRpg.Services.Impl/FieldSaveHelper.cs
- Joinrpg/Helpers/ModelStateExtensions.cs
- Joinrpg/Views/Shared/DisplayTemplates/FieldValueViewModel.cshtml
- Joinrpg/Views/Shared/EditorTemplates/FieldValueViewModel.cshtml
> Fix two more bugs

- JoinRpg.DataModel/User.cs
- JoinRpg.Markdown.Test/LinkRendererTest.cs
- JoinRpg.Services.Export/AutoFrontEnd/ColumnCreator.cs
- JoinRpg.Services.Export/AutoFrontEnd/TableColumn.cs
- JoinRpg.Services.Export/BackEnds/ClosedXmlExcelBackend.cs
- JoinRpg.Services.Export/BackEnds/CsvBackend.cs
- JoinRpg.Services.Export/Internal/Cell.cs
- JoinRpg.Services.Export/Internal/TableGenerator.cs
- JoinRpg.Services.Interfaces/IExportDataService.cs
- Joinrpg.Markdown/LinkerParser.cs
- Joinrpg/Helpers/JoinrpgMarkdownLinkRenderer.cs
- Joinrpg/Models/Exporters/CustomExporter.cs
- Joinrpg/Views/Shared/_Layout.cshtml
> Enable percent commands

- JoinRpg.Dal.Impl/MyUserStore.cs
- JoinRpg.DataModel/JoinRpg.DataModel.csproj
- JoinRpg.DataModel/Security.cs
- JoinRpg.Domain/CharacterFields/FieldWithValue.cs
- JoinRpg.Domain/FieldExtensions.cs
- JoinRpg.Helpers.Web/HtmlSanitizeHelper.cs
- JoinRpg.Helpers/UnSafeHtml.cs
- JoinRpg.Services.Impl/UserServiceImpl.cs
- JoinRpg.Services.Interfaces/IUserService.cs
- Joinrpg/Areas/Admin/AdminAreaRegistration.cs
- Joinrpg/Areas/Admin/Controllers/UsersController.cs
- Joinrpg/Areas/Admin/Models/ChangeEmailModel.cs
- Joinrpg/Controllers/UserController.cs
- Joinrpg/Helpers/AdminAuthorizeAttribute.cs
- Joinrpg/JoinRpg.Web.csproj
- Joinrpg/Models/AclViewModel.cs
- Joinrpg/Models/CustomFieldsViewModels.cs
- Joinrpg/Models/UserProfileViewModel.cs
- Joinrpg/Views/GameTools/Apis.cshtml
- Joinrpg/Views/Shared/DisplayTemplates/FieldValueViewModel.cshtml
- Joinrpg/Views/Shared/EditorTemplates/ProjectDropDown.cshtml
- Joinrpg/Views/User/AddToProject.cshtml
- Joinrpg/Views/User/ChangeEmailForm.cshtml
- Joinrpg/Views/User/Details.cshtml
fixes #320 
fixes #318 
Позволяет админу менять email пользователям
> Small fixes january

- JoinRpg.Helpers.Web/HtmlSanitizeHelper.cs
- JoinRpg.Markdown.Test/JoinRpg.Markdown.Test.csproj
- JoinRpg.Markdown.Test/ListTest.cs
> Allow more safe attributes in Html Sanitizer

- Joinrpg/Models/TargetedSearchResultViewModel.cs
fixes #408 
+ "..." in the end would never appear even when a string was truncated
> One more fix for search in details

- JoinRpg.Domain/FieldExtensions.cs
- Joinrpg/Controllers/ForumController.cs
- Joinrpg/Models/Characters/CharacterDetailsViewModel.cs
- Joinrpg/Models/Characters/CharacterGroupListViewModel.cs
- Joinrpg/Views/Claim/Edit.cshtml
- Joinrpg/Views/GameTools/Apis.cshtml
- Joinrpg/Views/Shared/DisplayTemplates/CharacterParentGroupsViewModel.cshtml
- Joinrpg/Views/Shared/DisplayTemplates/ClaimFeeViewModel.cshtml
- Joinrpg/Views/Shared/_PlayerMenuPartial.cshtml
fixes #410 
fixes #386 
fixes #251 
fixes #385
> A lot of small fixes for Release 2016.6

- JoinRpg.Domain/ClaimSourceExtensions.cs
- Joinrpg/Controllers/CharacterController.cs
- Joinrpg/Models/Characters/CharacterViewModels.cs
- Joinrpg/Views/Character/Edit.cshtml
- Joinrpg/Views/GameGroups/Details.cshtml
> Fix npc fields

- JoinRpg.DataModel/ProjectField.cs
- Joinrpg/Models/GameFieldViewModel.cs
- Joinrpg/Views/CharacterList/_CharacterList.cshtml
- Joinrpg/Views/Shared/DisplayTemplates/FieldValueViewModel.cshtml
- Joinrpg/Views/Shared/EditorTemplates/FieldValueViewModel.cshtml
> Add new field type number

- JoinRpg.DataModel/PlotFolder.cs
- JoinRpg.Domain/TagExtensions.cs
- JoinRpg.Services.Impl/PlotServiceImpl.cs
- Joinrpg/Controllers/PlotController.cs
- Joinrpg/Models/Plot/EditPlotFolderViewModel.cs
> Fix a lot of problems with tags

- JoinRpg.Dal.Impl/Migrations/201705040856203_VersionedPlot.cs
Fix migration of versioned plot
> Fix migration

- JoinRpg.Domain/UserExtensions.cs
- JoinRpg.Services.Export/BackEnds/CsvBackend.cs
- JoinRpg.Services.Export/BackEnds/ExcelBackendBase.cs
- JoinRpg.Services.Export/ExportDataServiceImpl.cs
- JoinRpg.Services.Export/Internal/IGeneratorBackend.cs
- JoinRpg.Services.Export/Internal/TableGenerator.cs
- JoinRpg.Services.Interfaces/IExportDataService.cs
- JoinRpg.Web.Test/JoinRpg.Web.Test.csproj
- Joinrpg/Controllers/AclController.cs
- Joinrpg/Controllers/ClaimController.cs
- Joinrpg/Controllers/Common/ControllerGameBase.cs
- Joinrpg/Controllers/UserController.cs
- Joinrpg/Models/AclViewModel.cs
- Joinrpg/Models/ClaimViewModel.cs
- Joinrpg/Models/Exporters/CharacterListForAutomaticExporter.cs
- Joinrpg/Models/Exporters/CustomExporter.cs
- Joinrpg/Models/UserProfileViewModel.cs
- Joinrpg/Views/Shared/DisplayTemplates/UserProfileDetailsViewModel.cshtml
- Joinrpg/Views/User/Details.cshtml
fixes #524 
fixes #529 
fixes #528
> Small 2017 9

- JoinRpg.Services.Impl.Test/JoinRpg.Services.Impl.Test.csproj
- JoinRpg.Services.Impl.Test/Properties/AssemblyInfo.cs
- JoinRpg.Services.Impl.Test/SearchKeywordsResolverTest.cs
- JoinRpg.Services.Impl/JoinRpg.Services.Impl.csproj
- JoinRpg.Services.Impl/Search/CharacterGroupsProvider.cs
- JoinRpg.Services.Impl/Search/CharacterProvider.cs
- JoinRpg.Services.Impl/Search/ClaimsByIdProvider.cs
- JoinRpg.Services.Impl/Search/SearchKeywordsResolver.cs
- JoinRpg.Services.Impl/Search/SearchServiceImpl.cs
- JoinRpg.Services.Impl/Search/UserSearchProvider.cs
- JoinRpg.Services.Impl/Search/WorldObjectProviderBase.cs
- JoinRpg.Services.Interfaces/Search/ISearchResult.cs
- Joinrpg.sln
- Joinrpg/Models/TargetedSearchResultViewModel.cs
> Search by Id

- JoinRpg.DataModel.Mocks/MockedProject.cs
- JoinRpg.DataModel/ProjectField.cs
- JoinRpg.Web.Test/CustomFieldsViewModelTest.cs
- Joinrpg/Models/CustomFieldsViewModels.cs
- Joinrpg/Models/Exporters/CharacterListExporterBase.cs
- Joinrpg/Models/Exporters/CustomExporter.cs
- Joinrpg/Views/GameField/Index.cshtml
- Joinrpg/Views/Shared/DisplayTemplates/FieldValueViewModel.cshtml
- Joinrpg/Views/Shared/DisplayTemplates/User.cshtml
- Joinrpg/Views/Shared/EditorTemplates/FieldValueViewModel.cshtml
fixes #558 
fixes #556 
fixes #67 
fixes #552 
fixes #548
> Small 2017 10

- JoinRpg.Services.Impl/ClaimServiceImpl.cs
- Joinrpg/App_Code/SearchableDropdownMvcHelper.cs
- Joinrpg/JoinRpg.Web.csproj
- Joinrpg/Models/CheckIn/CheckInVewModel.cs
- Joinrpg/Views/CheckIn/Index.cshtml
- Joinrpg/Views/CheckIn/SecondRole.cshtml
- Joinrpg/Views/Claim/Edit.cshtml
> Registration2

- JoinRpg.Data.Write.Interfaces/Properties/AssemblyInfo.cs
- JoinRpg.Services.Impl/FieldSetupServiceImpl.cs
- JoinRpg.Services.Interfaces/IFieldSetupService.cs
- JoinRpg.Web.XGameApi.Contract/JoinRpg.Web.XGameApi.Contract.xml
- JoinRpg.Web.XGameApi.Contract/ProjectFieldVariant.cs
- Joinrpg/Controllers/GameFieldController.cs
- Joinrpg/Controllers/GameGroupsController.cs
- Joinrpg/Controllers/XGameApi/MetaDataApicontroller.cs
- Joinrpg/Helpers/MagicControlHelper.cs
- Joinrpg/Models/CustomFieldsViewModels.cs
- Joinrpg/Models/GameFieldViewModel.cs
- Joinrpg/Views/GameField/Create.cshtml
- Joinrpg/Views/GameField/CreateValue.cshtml
- Joinrpg/Views/GameField/EditValue.cshtml
- Joinrpg/Views/GameField/FieldList.cshtml
- Joinrpg/Views/Shared/DisplayTemplates/FieldValueViewModel.cshtml
- Joinrpg/Views/Shared/_MasterMenuPartial.cshtml
- Joinrpg/Views/Shared/_PlotForCharacterPartial.cshtml
fixes #632
fixes #631 
fixes #630 
fixes #627 
fixes #612 
fixes #579
> Small 2017 2

- Joinrpg/JoinRpg.Web.csproj
- Joinrpg/packages.config
> Remove unused OWIN integration References (Facebook, MS Auth)

- Joinrpg/Models/ApisIndexViewModel.cs
> remove last bit of csv token-protected export

- .editorconfig
- JoinRpg.Services.Email/EmailServiceImpl.cs
- JoinRpg.Services.Impl/ForumServiceImpl.cs
- JoinRpg.Services.Impl/PlotServiceImpl.cs
- Joinrpg/App_Start/SwaggerConfig.cs
- Joinrpg/Controllers/AccountController.cs
- Joinrpg/Controllers/AclController.cs
- Joinrpg/Controllers/PlotController.cs
- Joinrpg/Models/GameFieldViewModel.cs
- Joinrpg/Models/Plot/AddPlotElementViewModel.cs
- Joinrpg/Models/Plot/AddPlotFolderViewModel.cs
- Joinrpg/Views/GameField/FieldList.cshtml
- Joinrpg/Views/Plot/EditElement.cshtml
- Joinrpg/Views/Shared/DisplayTemplates/CharacterGroupDetailsViewModel.cshtml
- Joinrpg/Views/Shared/EditorTemplates/MarkdownString.cshtml
fixes #621 
fixes #590 
fixes #625 
fixes #635 
fixes #557 
fixes #550 
fixes #474
> Small 2017 13

- JoinRpg.DataModel.Mocks/MockedProject.cs
- JoinRpg.DataModel/ProjectAcl.cs
- JoinRpg.Services.Impl/ClaimServiceImpl.cs
- JoinRpg.Services.Impl/ProjectService.cs
- JoinRpg.Services.Interfaces/IProjectService.cs
- Joinrpg/Controllers/AclController.cs
- Joinrpg/Controllers/CharacterListController.cs
- Joinrpg/Controllers/UserController.cs
- Joinrpg/JoinRpg.Web.csproj
- Joinrpg/Views/Acl/ForceSet.cshtml
- Joinrpg/Views/Shared/_PlayerMenuPartial.cshtml
fixes #653 
fixes #652 
fixes #650 
fixes #640
> Small 2017 14-1

- Joinrpg/Controllers/GameFieldController.cs
- Joinrpg/Models/GameFieldViewModel.cs
- Joinrpg/Views/Claim/Add.cshtml
- Joinrpg/Views/Claim/_ClaimFieldsSubtotal.cshtml
fixes #664 
fixes #665 
fixes #666
> Price for custom fields fixes

- JoinRpg.Domain/CharacterFields/FieldSaveHelper.cs
> Notifications fix when empty fields were not changed

- JoinRpg.Domain/CharacterFields/FieldWithValue.cs
- JoinRpg.Services.Email/EmailServiceImpl.cs
fixes #674 
United diff looks horrible because of changes to spacing. You'd better look at the commits individually.
> Aligned mail titles, improved checkbox display strings

- JoinRpg.DataModel/FinanceOperation.cs
- JoinRpg.Domain/FinanceExtensions.cs
- Joinrpg/Content/Site.css
- Joinrpg/Models/ClaimViewModel.cs
- Joinrpg/Models/CustomFieldsViewModels.cs
- Joinrpg/Models/FinanceModels.cs
- Joinrpg/Models/Print/PrintCharacterViewModel.cs
- Joinrpg/Scripts/claim.js
- Joinrpg/Views/Shared/DisplayTemplates/ClaimFeeViewModel.cshtml
> #683 -- draft preview

- Joinrpg/Models/ClaimViewModel.cs
- Joinrpg/Scripts/claim.js
- Joinrpg/Views/Claim/Edit.cshtml
- Joinrpg/Views/Shared/DisplayTemplates/ClaimFeeViewModel.cshtml
#689 Fee row in claim editor visibility tuning
> Fee visibility

- Joinrpg/Controllers/PlotController.cs
- Joinrpg/Views/CharacterList/_CharacterList.cshtml
- Joinrpg/Views/GameField/Create.cshtml
fixes #700 
fixes #701 
fixes #697
> Small 2017 16

- Joinrpg/App_Start/RouteConfig.cs
- Joinrpg/Areas/Admin/Controllers/AdminHomeController.cs
- Joinrpg/Areas/Admin/Controllers/ProjectListController.cs
- Joinrpg/Areas/Admin/Views/AdminHome/Index.cshtml
- Joinrpg/Areas/Admin/Views/ProjectList/Index.cshtml
- Joinrpg/Areas/Admin/Views/_ViewStart.cshtml
- Joinrpg/JoinRpg.Web.csproj
- Joinrpg/Views/Menu/MyProjectDropdown.cshtml
- Joinrpg/Views/Shared/ProjectCard.cshtml
- Joinrpg/Views/Shared/_Layout.cshtml
- Joinrpg/Views/Shared/_LoginPartial.cshtml
> Add admin list of games

- JoinRpg.Services.Impl/DbServiceImplBase.cs
- Joinrpg/Models/AddClaimViewModel.cs
- Joinrpg/Models/ProjectViewModels.cs
- Joinrpg/Views/Claim/Add.cshtml
- Joinrpg/Views/Shared/ProjectCard.cshtml
> Fix root claims ui

- Joinrpg/Views/Claim/Edit.cshtml
- Joinrpg/Views/Plot/EditElementPartial.cshtml
> hide last modified time for published plots

- JoinRpg.Domain/ProjectEntityExtensions.cs
- Joinrpg/Controllers/ForumController.cs
- Joinrpg/Models/Characters/CharacterGroupReportViewModel.cs
- Joinrpg/Models/ClaimListItemViewModel.cs
- Joinrpg/Models/Exporters/ClaimListItemViewModelExporter.cs
- Joinrpg/Models/Exporters/CustomExporter.cs
fixes #738 
fixes #732 
fixes #742
> Small fixes 2018 01 28

- Joinrpg/Models/Accommodation/AccRequestViewModel.cs
- Joinrpg/Scripts/rooms.js
- was not possible to handle accommodation requests with number of inhabitants equal to free space
- incorrect display of user's payment information
> Fixing accommodation UI bugs:

- JoinRpg.Dal.Impl/Repositories/AccommodationRepositoryImpl.cs
- JoinRpg.Dal.Impl/Repositories/ClaimsRepositoryImpl.cs
- JoinRpg.Data.Interfaces/IAccommodationRepository.cs
- JoinRpg.Data.Interfaces/IClaimsRepository.cs
- JoinRpg.Services.Impl/ClaimImplBase.cs
- JoinRpg.Services.Impl/CommentHelper.cs
- JoinRpg.Services.Impl/ForumServiceImpl.cs
- JoinRpg.Services.Impl/JoinRpg.Services.Impl.csproj
- Joinrpg/App_Start/RouteConfig.cs
- Joinrpg/Controllers/AccommodationTypeController.cs
- Joinrpg/Controllers/ClaimListController.cs
- Joinrpg/Models/Accommodation/AccommodationListViewModel.cs
- Joinrpg/Models/Accommodation/RoomTypeViewModel.cs
- Joinrpg/Views/AccommodationType/Index.cshtml
- Joinrpg/Views/AccommodationType/_RoomTypeDetails.cshtml
> Fixes 2018 02 20

- Joinrpg/Content/Site.css
- Joinrpg/Scripts/rooms.js
- Joinrpg/Views/AccommodationType/EditRoomTypeRooms.cshtml
- Joinrpg/Views/AccommodationType/Index.cshtml
- Joinrpg/Views/AccommodationType/_OccupationDlg.cshtml
- Joinrpg/Views/AccommodationType/_RoomTypeDetails.cshtml
- non-accommodated requests are now scrolled vertically
- look and feel of room types table
> Accommodation UI appearance fixes

- Joinrpg/App_Start/Startup.Auth.cs
- Joinrpg/JoinRpg.Web.csproj
- Joinrpg/packages.config
> vk auth fixed (using new lib)

- JoinRpg.DataModel.Mocks/JoinRpg.DataModel.Mocks.csproj
- JoinRpg.DataModel.Mocks/MockHelpers.cs
- JoinRpg.DataModel.Mocks/MockedProject.cs
- JoinRpg.Domain.Test/ShouldyDataModelExtensions.cs
- JoinRpg.Domain/CharacterFields/CustomFieldsExtensions.cs
- JoinRpg.Domain/CharacterFields/FieldSaveHelper.cs
- JoinRpg.Domain/ProjectEntityExtensions.cs
- JoinRpg.Services.Impl/ClaimServiceImpl.cs
- JoinRpg.Services.Impl/ProjectService.cs
- JoinRpg.Services.Interfaces/AddCharacterRequest.cs
- JoinRpg.Services.Interfaces/IClaimService.cs
- JoinRpg.Services.Interfaces/IProjectService.cs
- JoinRpg.Services.Interfaces/JoinRpg.Services.Interfaces.csproj
- JoinRpg.Web.Test/AddClaimViewModelTest.cs
- JoinRpg.Web.Test/CharacterViewModelTest.cs
- JoinRpg.Web.Test/CustomFieldsViewModelTest.cs
- JoinRpg.Web.Test/JoinRpg.Web.Test.csproj
- JoinRpg.Web.Test/ShouldlyFieldValueViewModelExtensions.cs
- Joinrpg/Controllers/CharacterController.cs
- Joinrpg/Controllers/Common/ControllerBase.cs
- Joinrpg/Controllers/Common/ControllerGameBase.cs
- Joinrpg/Models/Characters/CharacterViewModels.cs
- Joinrpg/Models/CustomFieldsViewModels.cs
- Joinrpg/Views/Character/Create.cshtml
- Joinrpg/Views/Claim/Add.cshtml
fixes #802
fixes #801
fixes #800
> Sapsan changes

- JoinRpg.Services.Impl/ProjectService.cs
> Improve character groups deletion

- JoinRpg.Services.Impl/ProjectService.cs
> Снятие кастомной подписки на заявки при удалении мастера из проекта

- Joinrpg/Models/Characters/CharacterListItemViewModel.cs
- Joinrpg/Models/Exporters/CharacterListExporterBase.cs
- Joinrpg/Models/Exporters/CustomExporter.cs
> Add responsible master to excel export

- JoinRpg.Services.Impl/ClaimServiceImpl.cs
- JoinRpg.Services.Interfaces/IClaimService.cs
- Joinrpg/Controllers/ClaimController.cs
- Joinrpg/Models/ClaimViewModel.cs
- Joinrpg/Models/CommentModels.cs
- Joinrpg/Views/Claim/Edit.cshtml
- Joinrpg/Views/Claim/MasterDenialOperationPartial.cshtml
fixes #726 
Добавлена возможность удаления персонажа при отклонении заявки.
> fixes #726

- JoinRpg.Dal.Impl/Repositories/CharacterRepositoryImpl.cs
- JoinRpg.Data.Interfaces/ICharacterRepository.cs
- JoinRpg.Web.XGameApi.Contract/CharacterInfo.cs
- JoinRpg.Web.XGameApi.Contract/JoinRpg.Web.XGameApi.Contract.xml
- Joinrpg/Controllers/XGameApi/CharacterApiController.cs
> add character name to api

- JoinRpg.Services.Impl/AntiSpamServiceImpl.cs
- JoinRpg.Services.Impl/Services.cs
- JoinRpg.Services.Interfaces/IAntiSpamService.cs
- JoinRpg.Web.XGameApi.Contract/IsLarperRequestModel.cs
- JoinRpg.Web.XGameApi.Contract/JoinRpg.Web.XGameApi.Contract.csproj
- Joinrpg/Controllers/XGameApi/AntiSpamServiceController.cs
- Joinrpg/JoinRpg.Web.csproj
Как обсуждали с Хлень для бота @noonesfriend_bot
> Добавлена API, которая может отвечать на вопрос «ролевик ли Х»

- JoinRpg.Services.Impl/CharacterServiceImpl.cs
- JoinRpg.Services.Impl/EmailHelpers.cs
- JoinRpg.Services.Impl/ProjectService.cs
- JoinRpg.Services.Impl/Services.cs
- JoinRpg.Services.Interfaces/ICharacterService.cs
- JoinRpg.Services.Interfaces/IProjectService.cs
- JoinRpg.Services.Interfaces/Notification/ClaimEmail.cs
- Joinrpg/Controllers/CharacterController.cs
- Joinrpg/Controllers/FinancesController.cs
- Joinrpg/Controllers/XGameApi/CharacterApiController.cs
- Joinrpg/Controllers/XGameApi/CheckInController.cs
- Joinrpg/Controllers/XGameApi/MetaDataApicontroller.cs
- Joinrpg/Filter/XGameMasterAuthorize.cs
- Joinrpg/JoinRpg.Web.csproj
> Add method that allows master to set fields using API

- JoinRpg.Dal.Impl/Repositories/ProjectRepository.cs
- JoinRpg.Data.Interfaces/IProjectRepository.cs
- JoinRpg.Data.Interfaces/ProjectWithUpdateDateDto.cs
- JoinRpg.Helpers.Web/BooleanRequired.cs
- JoinRpg.Helpers.Web/JoinRpg.Helpers.Web.csproj
- JoinRpg.WebPortal.Models/AccountViewModels.cs
- JoinRpg.WebPortal.Models/ProjectCreateViewModel.cs
- Joinrpg/Areas/Admin/Controllers/AdminHomeController.cs
- Joinrpg/Areas/Admin/Views/AdminHome/Index.cshtml
- Joinrpg/Areas/Admin/Views/AdminHome/StaleGames.cshtml
- Joinrpg/JoinRpg.Web.csproj
> Inactiveprojects

- JoinRpg.Dal.Impl/Repositories/ClaimPredicates.cs
- JoinRpg.Dal.Impl/Repositories/ProjectRepository.cs
- JoinRpg.Data.Interfaces/IClaimsRepository.cs
> Remove inactive claims from front page

- Joinrpg/external/joinrpg-api.js
fixes #932 
remove global $-variable requirement
> ISSUE-932 fix jquery.noConflict() problem

- JoinRpg.Web.Test/Autofac/AutofacConfigurationTest.cs
- JoinRpg.Web.Test/Autofac/AutofacFixture.cs
- JoinRpg.Web.Test/JoinRpg.Web.Test.csproj
- JoinRpg.WebPortal.Managers/Registration.cs
- Joinrpg/App_Start/IdentityConfig.cs
- Joinrpg/App_Start/WebModule.cs
- Joinrpg/Controllers/Common/ControllerBase.cs
- Joinrpg/Controllers/Common/ControllerGameBase.cs
- Joinrpg/Views/Home/Index.cshtml
Добавлены юнит-тесты на autofac
Поправлена проблема с редактором полей
fixes #947
> Поправить редактор полей

- JoinRpg.DataModel/Project/Project.cs
- JoinRpg.DataModel/Project/ProjectDetails.cs
- Joinrpg.Web.Identity/MyUserStore.cs
> Исправление ошибки регистрации

- Joinrpg.Web.Identity/MyUserStore.cs
> Снова фиксим регистрацию

- JoinRpg.Dal.Impl/MyDbContext.cs
- JoinRpg.Services.Impl/CharacterServiceImpl.cs
- JoinRpg.Services.Impl/FieldSetupServiceImpl.cs
- JoinRpg.Services.Impl/ProjectService.cs
- JoinRpg.WebPortal.Models/Characters/CharacterViewModels.cs
- JoinRpg.WebPortal.Models/CommentModels.cs
- JoinRpg.WebPortal.Models/ProjectViewModels.cs
- Joinrpg/Controllers/ClaimController.cs
- Joinrpg/Controllers/Common/ControllerGameBase.cs
- Joinrpg/Controllers/GameFieldController.cs
- Joinrpg/Views/Character/Create.cshtml
- Joinrpg/Views/Character/Edit.cshtml
- Joinrpg/Views/Claim/Edit.cshtml
- Joinrpg/Views/Claim/MasterDenialOperationPartial.cshtml
- Улучшен UI отклонения заявки
- Более правильно работает редактирование имени персонажа
- Поправлены баги
> Sunday night bugfix

- JoinRpg.WebPortal.Managers/Schedule/SchedulePageManager.cs
- JoinRpg.WebPortal.Managers/Schedule/SchedulePageViewModelBuilder.cs
- JoinRpg.WebPortal.Models/Schedules/AppointmentViewModel.cs
- JoinRpg.WebPortal.Models/Schedules/SchedulePageViewModel.cs
- JoinRpg.WebPortal.Models/Schedules/TableHeaderViewModel.cs
- Joinrpg/Content/AppointmentDetails.css
- Joinrpg/Content/FullScreen.css
- Joinrpg/Content/Scheduler.css
- Joinrpg/JoinRpg.Web.csproj
- Joinrpg/Views/ShowSchedule/FullScreen.cshtml
- Joinrpg/Views/ShowSchedule/Scheduler.cshtml
- Joinrpg/Views/ShowSchedule/_AppointmentDetailsPartial.cshtml
- Joinrpg/Views/ShowSchedule/_AppointmentPartial.cshtml
1. Layout fixes
2. Appointments look
3. Description popup in fullscreen mode
> Scheduler improvements

- JoinRpg.Services.Impl/FinanceOperationsImpl.cs
After money transfer from a claim to another claim trying to fix fee of destination claim
> Fee fixing issue

- CONTRIBUTING.MD
- The Local DB direct download link has been added to instructions list
- The error with joinrpg.mdf database creation has been mentioned in application startup section
- Additional text explanations have been added to another points
> Altered CONTRIBUTING.md in order to take into account some additional points

- CONTRIBUTING.MD
It is important to have the latest version of DB in order to avoid unexpected bugs. Mentioned it in documentation
> Information about SQL Server 2017 cumulative updates has been added to CONTRIBUTING.md

- CONTRIBUTING.MD
- README.md
- The outdated information about license has been removed from README.md
- The 'Code guidelines' section has been added to CONTRIBUTING.md
> More edits to CONTRIBUTING.md and README.md

- JoinRpg.IntegrationTests/TestInfrastructure/Stubs/StubRecaptchaVerificator.cs
- JoinRpg.Portal/Controllers/AccountController.cs
- JoinRpg.Portal/Infrastructure/Authentication/IRecaptchaVerificator.cs
- JoinRpg.Portal/Infrastructure/Authentication/RecaptchaVerificator.cs
- JoinRpg.Portal/Views/Account/Register.cshtml
- JoinRpg.WebPortal.Models/AccountViewModels.cs
Do not show ReCAPTCHA, if private and public keys are not configured
correctly (settings in appsettings.json file). Key string values are
checked to correspond to certain format (numbers, letters, dash and
underscore, in the length of 40 symbols).
Code changes:
- AdditionalProperty - IsRecaptchaConfigured - has been added to the
controller and view-model
- Corresponding method ("IsRecaptchaConfigured") has been added to
RecaptchaVerificator
> ReCAPTCHA issue

- JoinRpg.WebPortal.Models/AccountViewModels.cs
- Email and Password "Required" attributes have been altered in order to
display error message on russian
> Error messages on russian have been added to Registration section

- JoinRpg.Portal/Controllers/AccommodationTypeController.cs
- JoinRpg.Portal/Views/AccommodationType/Index.cshtml
- JoinRpg.Portal/Views/AccommodationType/_RoomTypeDetails.cshtml
- JoinRpg.Portal/Views/Finances/Operations.cshtml
- JoinRpg.Portal/Views/Finances/_Operations.cshtml
- JoinRpg.WebPortal.Models/Accommodation/AccommodationListViewModel.cs
- JoinRpg.WebPortal.Models/ClaimListItemViewModel.cs
- JoinRpg.WebPortal.Models/Exporters/ClaimListItemViewModelExporter.cs
- add fullname to finance list page
- add full fee to claim export
> Add more information to some finance lists

- azure-pipelines.check.pr.yml
- src/JoinRpg.Portal/Controllers/GameGroupsController.cs
> Remove Newtonsoft.Json configuration (we are now using System.Text.Json)

- src/JoinRpg.Portal/Views/GameGroups/Index.cshtml
- src/JoinRpg.Portal/Views/GameGroups/_CharacterPartial.cshtml
> fix layout in roles

- src/JoinRpg.Portal/Views/Claim/Add.cshtml
- src/JoinRpg.Services.Export/JoinRpg.Services.Export.csproj
> Fixed route to add claim

- src/JoinRpg.Portal/Views/Print/Index.cshtml
- src/JoinRpg.Services.Export/JoinRpg.Services.Export.csproj
> Fix routes in print section

- src/JoinRpg.Portal/Views/GameField/_FieldNavigation.cshtml
- src/JoinRpg.Services.Export/JoinRpg.Services.Export.csproj
> Fix routing in fields setup

- src/JoinRpg.DataModel/Comment.cs
- src/JoinRpg.Portal/Views/Claim/ClaimOperationPartial.cshtml
- src/JoinRpg.Portal/Views/Claim/Edit.cshtml
- src/JoinRpg.Portal/Views/Claim/MasterDenialOperationPartial.cshtml
- src/JoinRpg.Services.Impl/ClaimServiceImpl.cs
- Show more validation errors
- Allow to approve claim w/o comment
> Improve claim form

- src/JoinRpg.IntegrationTests/Scenarios/CheckDateTimeMappingTest.cs
- src/JoinRpg.IntegrationTests/TestInfrastructure/JoinApplicationFactoryWithMockControllers.cs
- src/JoinRpg.IntegrationTests/TestInfrastructure/MockControllers/MockDateTimeController.cs
- src/JoinRpg.Portal/Startup.cs
fixes #1118 #1117
FIY:  @shinikage  обрати внимание
> Force russian localizaton

- src/JoinRpg.Portal/Controllers/AccountController.cs
> show correct error for recaptcha

- src/JoinRpg.Portal/Areas/Admin/Controllers/UsersController.cs
- src/JoinRpg.Services.Impl/UserServiceImpl.cs
- src/JoinRpg.Services.Interfaces/IUserService.cs
> Password change now use UserManager instread of changing in DB directly

- src/JoinRpg.Portal/Views/Shared/EditorTemplates/FieldValueViewModel.cshtml
- src/JoinRpg.Portal/Views/Shared/EditorTemplates/_SelectOptionDefPartial.cshtml
- src/JoinRpg.Portal/Views/Shared/EditorTemplates/_SelectOptionPartial.cshtml
> Fixing select/multiselect not working properly

- src/JoinRpg.Portal/Views/Account/_ExternalLoginsListPartial.cshtml
fixes #28 
VK button is now in primary style (white on blue)
> issue N28: Make VK button blue again

- src/JoinRpg.DataModel/ProjectFieldTypeHelper.cs
- src/JoinRpg.Domain/Exceptions.cs
- src/JoinRpg.Domain/FieldExtensions.cs
- src/JoinRpg.Domain/Schedules/ScheduleFieldExtensions.cs
- src/JoinRpg.Portal/Infrastructure/HealthChecks/HealthCheckLoadProjects.cs
- src/JoinRpg.Portal/Infrastructure/ModelStateExtensions.cs
- src/JoinRpg.Portal/Startup.cs
- src/JoinRpg.Portal/Views/Game/Edit.cshtml
- src/JoinRpg.Portal/Views/GameField/CreateValue.cshtml
- src/JoinRpg.Portal/Views/GameField/Edit.cshtml
- src/JoinRpg.Portal/Views/Shared/EditorTemplates/FieldValueViewModel.cshtml
- src/JoinRpg.Portal/Views/Shared/_Layout.cshtml
- src/JoinRpg.Services.Impl/FieldSetupServiceImpl.cs
- src/JoinRpg.WebPortal.Models/FieldSetup/GameFieldViewModel.cs
- src/Joinrpg.Dal.Migrate/Joinrpg.Dal.Migrate.csproj
- src/Joinrpg.Dal.Migrate/appsettings.json
> A lot of bugfixes

- src/JoinRpg.Portal/Controllers/AccountController.cs
- src/JoinRpg.Portal/Controllers/UserController.cs
> Fix some bugs in profile

- CONTRIBUTING.MD
- Added contributing step about `dotnet format`
- Normalized spaces and tabs in the CONTRIBUTING.MD
> Add dotnet format to Contributing guide

- src/JoinRpg.Portal/Views/Account/Register.cshtml
Make captcha required to unlock form submit button.
> Make reCaptcha required (possible resolve #1160)

- src/JoinRpg.Portal/Controllers/AclController.cs
- src/JoinRpg.Portal/Views/Acl/Delete.cshtml
- src/JoinRpg.Portal/Views/Acl/Index.cshtml
- src/JoinRpg.Services.Impl/ProjectService.cs
- src/JoinRpg.Services.Interfaces/AccessRequestBase.cs
- src/JoinRpg.WebPortal.Models/Masters/AclViewModel.cs
Not the best solution that closes #21
Adds buttons for masters, which can remove them from project masters.
> Add ability to remove yourself from masters

- src/JoinRpg.Dal.Impl/Repositories/ProjectRepository.cs
- src/JoinRpg.Data.Interfaces/IProjectRepository.cs
- src/JoinRpg.Portal/Menu/MainMenuViewComponent.cs
- src/JoinRpg.Portal/Models/MainMenuViewModel.cs
- src/JoinRpg.Portal/Views/Home/BrowseGames.cshtml
- src/JoinRpg.Portal/Views/Shared/Components/MainMenu/MainMenu.cshtml
- src/JoinRpg.Portal/wwwroot/css/site.css
- src/JoinRpg.WebPortal.Models/ProjectViewModels.cs
Closes #377,  possible close #248:
> Add game archive button

- .config/dotnet-tools.json
- JoinRpg.PrimitiveTypes/SingleValueType.cs
- JoinRpg.PrimitiveTypes/VkId.cs
- src/JoinRpg.WebPortal.Models/UserLoginInfoViewModel.cs
https://github.com/dotnet/format/releases/tag/v5.0.211103
> update dotnet-format to v5.0.211103

- src/JoinRpg.Portal/Areas/Admin/Controllers/UsersController.cs
Restore some controller actions, which have been required for user verification button.
> Restore missing controller actions

- src/JoinRpg.Helpers/VirtualOrderContainer.cs
- src/JoinRpg.Services.Impl/FieldSetupServiceImpl.cs
> Fix problem with schedule global does not follow adding/removing fields

- src/Joinrpg.AspNetCore.Helpers/FormCollectionHelpers.cs
> Fix problem with multivalues

- src/JoinRpg.Portal/Controllers/AccommodationTypeController.cs
- src/JoinRpg.Portal/Controllers/UserProfile/UserController.cs
- src/JoinRpg.Portal/Startup.cs
- src/JoinRpg.Portal/Views/AccommodationType/EditRoomTypeRooms.cshtml
- src/JoinRpg.Portal/Views/Claim/Edit.cshtml
- src/JoinRpg.Portal/wwwroot/Scripts/edit-funcs.js
- src/JoinRpg.Portal/wwwroot/Scripts/rooms.js
- src/JoinRpg.Services.Impl/ClaimServiceImpl.cs
- src/JoinRpg.WebPortal.Models/ClaimViewModel.cs
> New bunch of bug fixes

- src/JoinRpg.Portal/Controllers/AccommodationTypeController.cs
- src/JoinRpg.Portal/Controllers/UserProfile/UserController.cs
- src/JoinRpg.Portal/Startup.cs
- src/JoinRpg.Portal/Views/AccommodationType/EditRoomTypeRooms.cshtml
- src/JoinRpg.Portal/Views/Claim/Edit.cshtml
- src/JoinRpg.Portal/wwwroot/Scripts/edit-funcs.js
- src/JoinRpg.Portal/wwwroot/Scripts/rooms.js
- src/JoinRpg.Services.Impl/ClaimServiceImpl.cs
- src/JoinRpg.Services.Impl/ProjectService.cs
- src/JoinRpg.WebPortal.Models/ClaimViewModel.cs
- src/JoinRpg.WebPortal.Models/ProjectCreateViewModel.cs
> Fix wording on project creation

- src/JoinRpg.Portal/Startup.cs
fixes #1320
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer
> Add forwarding headers 

- src/JoinRpg.Portal/Startup.cs
> Configure correct forwarding headers

- src/JoinRpg.DataModel/Finances/FinanceOperation.cs
- src/JoinRpg.Portal/Controllers/Money/PaymentsController.cs
- src/JoinRpg.Portal/Infrastructure/ConfigurationAdapter.cs
- src/JoinRpg.Portal/Views/Account/Register.cshtml
- src/JoinRpg.Portal/Views/Finances/_PayOnlineDialog.cshtml
- src/JoinRpg.Portal/appsettings.json
- src/JoinRpg.Portal/wwwroot/css/site.css
- src/JoinRpg.Services.Impl/PaymentsService.cs
- src/JoinRpg.Services.Interfaces/IPaymentsService.cs
- src/JoinRpg.WebPortal.Models/ClaimViewModel.cs
- src/JoinRpg.WebPortal.Models/Money/Enums.cs
- src/JoinRpg.WebPortal.Models/Money/FinanceViewModelsExtensions.cs
- src/JoinRpg.WebPortal.Models/Money/PaymentViewModel.cs
- src/PscbApi/ApiConfiguration.cs
- src/PscbApi/BankApi.cs
- src/PscbApi/IBankSecretsProvider.cs
- src/PscbApi/Models/PscbPaymentMethod.cs
- recaptcha script in case of missed recaptcha config fix
- claim view model nullables
- new state for finance operations that wasn't completed by user (fixes payments that were not updatable)
- integration with QR-code payments by PSCB
> Fixes for new Core version

- src/JoinRpg.Helpers/DisplayAttributeHelper.cs
- src/JoinRpg.Portal/Views/Shared/DisplayTemplates/ClaimFullStatusView.cshtml
- src/JoinRpg.Portal/Views/ShowSchedule/_AppointmentPartial.cshtml
- src/JoinRpg.WebPortal.Models/Exporters/CustomExporter.cs
> Fix nullability for enums

- .config/dotnet-tools.json
https://github.com/dotnet/format/releases/tag/v5.1.225507
> Update dotnet-format to v5.1.225507

- src/JoinRpg.Portal/Controllers/GameFieldController.cs
- src/JoinRpg.Portal/Views/GameField/FieldList.cshtml
- src/JoinRpg.Portal/wwwroot/Scripts/editfieldvalues.js
> Fixes of invalid urls in field editing area

- src/JoinRpg.Dal.Impl/Repositories/CharacterRepositoryImpl.cs
- src/JoinRpg.Portal/Controllers/CharacterController.cs
- src/JoinRpg.Portal/Infrastructure/XApi/Swagger.cs
fixes #1403
fix crash in API
Improve swagger
> A lot of bug fixes

- src/JoinRpg.Portal/Controllers/UserProfile/ManageController.cs
- src/JoinRpg.Portal/Views/Manage/SetupProfile.cshtml
- src/JoinRpg.WebPortal.Models/UserProfile/EditUserProfileViewModel.cs
- src/JoinRpg.WebPortal.Models/UserProfile/ManageMessageId.cs
> Add error message with fail to link social account

- src/JoinRpg.Portal/Controllers/UserProfile/ManageController.cs
- src/JoinRpg.Portal/appsettings.json
- src/JoinRpg.WebPortal.Models/UserProfile/UserLoginInfoViewModel.cs
> Fix casing in vkontakte provider name

- src/JoinRpg.DataModel/Claim.cs
- src/JoinRpg.Portal/Controllers/ClaimController.cs
- src/JoinRpg.Portal/Controllers/ClaimListController.cs
- src/JoinRpg.Portal/Views/Claim/Edit.cshtml
- src/JoinRpg.Portal/Views/Claim/_ClaimAccommodation.cshtml
- src/JoinRpg.Portal/Views/Claim/_ClaimAccommodationTypeChange.cshtml
- src/JoinRpg.Portal/Views/Claim/_ClaimIncomingInvites.cshtml
- src/JoinRpg.Portal/Views/Claim/_ClaimOutgoingInvites.cshtml
- src/JoinRpg.Services.Impl/AccommodationInviteServiceImpl.cs
- src/JoinRpg.Services.Impl/ClaimServiceImpl.cs
- src/JoinRpg.Services.Interfaces/IClaimService.cs
- src/JoinRpg.WebPortal.Models/Accommodation/ClaimAccommodationViewModel.cs
- src/JoinRpg.WebPortal.Models/ClaimViewModel.cs
- src/JoinRpg.WebPortal.Models/InviteRequestViewModel.cs
1. Obsolete code removed.
2. Refactored layot of claim accommodation controls.
3. Refactored invitations backend.
4. Button and backend for exiting from accommodation group.
> Breaking group of accommodation neighbours

- src/JoinRpg.Portal/Views/Shared/DisplayTemplates/PlotFolderListItemViewModel.cshtml
> Fix routing to plot folder tags

- src/JoinRpg.Portal/Controllers/CharacterController.cs
- src/JoinRpg.Portal/Views/Character/Create.cshtml
- src/JoinRpg.Portal/Views/Character/Edit.cshtml
- src/JoinRpg.WebPortal.Models/Characters/CharacterViewModels.cs
> Temporary disable new character group selector

- src/JoinRpg.Portal/Controllers/GameGroupsController.cs
- src/JoinRpg.Portal/Views/GameGroups/Report.cshtml
> Fix routing for group report

- Joinrpg.sln
- src/JoinRpg.Portal/Controllers/XGameApi/CheckInController.cs
- src/Joinrpg.Dal.Migrate/EfCore/MigrateEfCoreHostService.cs
- src/Joinrpg.Dal.Migrate/OneTimeOperationHostedServiceBase.cs
> Small fixes from AntonSmolkov branch

- .github/workflows/build_and_publish.yml
Update SemVer calculator script
> Update SemVer calculator script

- manifests/base/ingress.yaml
- manifests/dev/kustomization.yaml
- manifests/prod/kustomization.yaml
Resolves https://github.com/joinrpg/joinrpg-net/issues/1757
> Enable Let's encrypt

- src/JoinRpg.Services.Export/BackEnds/ClosedXmlExcelBackend.cs
- src/JoinRpg.Services.Export/JoinRpg.Services.Export.csproj
> Update ClosedXML to 0.96.0

- src/JoinRpg.Domain/ClaimExtensions.cs
- src/JoinRpg.Portal/Views/Claim/Edit.cshtml
- src/JoinRpg.Services.Impl/ClaimServiceImpl.cs
- src/JoinRpg.WebPortal.Models/Claims/ClaimViewModel.cs
> Fix problem with slot cant accept any claims if already have two

- src/JoinRpg.Portal/Controllers/ClaimController.cs
- src/JoinRpg.Services.Impl/CharacterServiceImpl.cs
- src/JoinRpg.Services.Impl/CreateProjectService.cs
- src/JoinRpg.Services.Impl/ProjectService.cs
- src/JoinRpg.Services.Interfaces/Characters/AddCharacterRequest.cs
- src/JoinRpg.WebComponents/EnumRadioButtonGroup.razor
* Now new project will have slot instead of group direct claims enabled
* Automatically select child slot if group disallowed direct claims
> A lot of improvements to slots

- src/JoinRpg.Domain/ClaimSourceExtensions.cs
- src/JoinRpg.Portal/Controllers/CharacterListController.cs
- src/JoinRpg.Portal/Controllers/ClaimListController.cs
- src/JoinRpg.Portal/Controllers/PlotListController.cs
- src/JoinRpg.Services.Impl/ForumServiceImpl.cs
- src/JoinRpg.WebPortal.Models/Helpers/JoinrpgMarkdownLinkRenderer.cs
> Fix order of character groups in contacts list (#1817)

- src/JoinRpg.Portal/Dockerfile
- src/JoinRpg.Portal/runtimeconfig.template.json
- src/JoinRpg.Services.Export/BackEnds/ClosedXmlExcelBackend.cs
- src/JoinRpg.Services.Export/JoinRpg.Services.Export.csproj
- No longer need to install libgdiplus
- Use Libration Sans as fallback font
> Update ClosedXml to 0.97.0, removing System.Drawing.Common dependency

- src/JoinRpg.Portal/Properties/launchSettings.json
> Включить devtunnel

- src/JoinRpg.Portal/Infrastructure/Authentication/AuthenticationConfigurator.cs
Password will be rehashed on next login
> Remove compatibility with old identity hash format.

- src/JoinRpg.Portal/Controllers/AccommodationPrintController.cs
- src/JoinRpg.Portal/Controllers/CharacterListController.cs
- src/JoinRpg.Portal/Controllers/ClaimListController.cs
- src/JoinRpg.Portal/Controllers/FinancesController.cs
- src/JoinRpg.Portal/Helpers/GeneratorResultHelper.cs
- src/JoinRpg.Services.Export/Internal/TableGenerator.cs
- src/JoinRpg.Services.Interfaces/IExportDataService.cs
(не нужен, лишние накладные расходы, а параллельность не повышается)
> Убран поток в генерации Excel 

- global.json
https://github.com/dotnet/sdk/issues/32598
> Move SDK to 7.0.304

- src/JoinRpg.Helpers/StaticStringHelpers.cs
- src/JoinRpg.Services.Impl/UserServiceImpl.cs
- src/JoinRpg.Web.XGameApi.Contract/PlayerContacts.cs
- src/JoinRpg.WebPortal.Models/Helpers/JoinrpgMarkdownLinkRenderer.cs
- src/JoinRpg.WebPortal.Models/UserProfile/UserProfileViewModel.cs
> Убрать символ @ из ссылки на телегу 

- src/JoinRpg.Portal/Controllers/Common/ControllerGameBase.cs
- src/JoinRpg.Portal/Controllers/GameSubscribeController.cs
- src/JoinRpg.Portal/Infrastructure/DiscoverFilters/SetIsProductionFilter.cs
- src/JoinRpg.Portal/Startup.cs
> Fix missing menus

- src/JoinRpg.Portal/Views/Acl/Index.cshtml
- src/JoinRpg.Services.Impl/ProjectAccessService.cs
- src/JoinRpg.WebPortal.Models/Masters/MastersListViewModel.cs
> Ошибки в логике удаления себя из мастеров и изменения своих прав в проекте 

- src/JoinRpg.Portal/Views/Character/Details.cshtml
- src/JoinRpg.Portal/Views/Shared/CharacterNavigation.cshtml
> Сделать так, чтобы можно было выделять имя персонажа в навигации

- src/JoinRpg.Dal.Impl/MyDbContext.cs
- src/JoinRpg.Dal.Impl/Repositories/GameRepositoryImplBase.cs
- src/JoinRpg.DataModel.Mocks/MockedProject.cs
- src/JoinRpg.DataModel/Character.cs
- src/JoinRpg.Domain.Test/AddClaim/MoveClaimValidationRulesTest.cs
- src/JoinRpg.WebPortal.Models.Test/CharacterViewModelTest.cs
- src/JoinRpg.WebPortal.Models.Test/CustomFieldsViewModelTest.cs
в теории должна вырасти скорость везде
> Убрать доставание заявок персонажа через левое ухо

- .gitignore
- scripts/create-new-environment.ps1
Адаптация к изменения https://github.com/kubernetes/kubernetes/pull/108309 (больше не генерируются автоматически секреты)
> В кубернетес больше не генерируются автоматически секреты

- src/JoinRpg.Domain/OrderingExtensions.cs
- src/JoinRpg.Helpers/VirtualOrderContainer.cs
- src/JoinRpg.Portal/Views/Plot/CreateHandout.cshtml
- src/JoinRpg.Portal/Views/Plot/EditElementPartial.cshtml
- src/JoinRpg.Portal/Views/Print/Character.cshtml
- src/JoinRpg.Portal/Views/Print/CharacterList.cshtml
- src/JoinRpg.Portal/Views/Print/CharacterListHeader.cshtml
- src/JoinRpg.Portal/Views/Print/PrintCharacter.cshtml
- src/JoinRpg.Portal/Views/Print/_CharacterHandout.cshtml
- src/JoinRpg.Portal/wwwroot/css/print.css
- src/JoinRpg.WebPortal.Models/Plot/AddPlotElementViewModel.cs
- src/JoinRpg.WebPortal.Models/Print/PrintCharacterViewModel.cs
1. Поправить сломанное добавление элементов раздатки.
2. Показывать кнопку публикации сюжета, даже если на публикацию нет прав (выключено)
3. Всегда показывать отв. мастера в распечатке (потому что он всегда должен быть)
4. Поправить сломанное предупреждение о том, что конверт не готов
5. Вводные группируются по сюжетам, если не задана сортировка
6. Распечатка загрузов переформатирована, добавлены стили, убрана распечатка групп с описаниями (если нужно можно добавить такую вводную всем).
> Обновления распечатки для игры Киев: Быль и не быль

- src/JoinRpg.BlobStorage/AvatarDownloader.cs
- src/JoinRpg.BlobStorage/S3AvatarStorageService.cs
- src/JoinRpg.BlobStorage/S3ClientFactory.cs
https://github.com/aws/aws-sdk-net/issues/3610
> Изменения в S3 

- src/JoinRpg.DataModel/Finances/FinanceOperation.cs
- src/JoinRpg.DataModel/Finances/FinanceOperationBankDetails.cs
- src/JoinRpg.Portal/Infrastructure/DailyJobs/PerformRecurrentPaymentMidnightJob.cs
- src/JoinRpg.Services.Impl/PaymentsService.cs
- src/JoinRpg.Services.Interfaces/IPaymentsService.cs
- Добавлены методы получения списка рекуррентных платежей и списка финансовых операций, связанных с рекуррентным платежом в `IPaymentsService`.
- Добавлено сохранение токена рекуррентного платежа, соответствующего стандартному периоду оплаты (1 месяц).
- Реализован сервис `PerformRecurrentPaymentMidnightJob`.
> Автоматическое списание по рекуррентным платежам

- .editorconfig
- src/JoinRpg.DataModel/Claim.cs
- src/JoinRpg.Domain/ClaimExtensions.cs
- src/JoinRpg.Services.Impl/PaymentsService.cs
...а также цинично увеличено число символов в строке до 120
> Исправлена проблема с использованием нетранслируемых свойств в предикате

- src/JoinRpg.Portal/Controllers/PlotController.cs
- src/JoinRpg.WebPortal.Models/Plot/AddPlotElementViewModel.cs
> При создании вводной добавлять заголовок и разделитель

- src/JoinRpg.Dal.Impl/Repositories/PlotRepositoryImpl.cs
- src/JoinRpg.Data.Interfaces/IPlotRepository.cs
- src/JoinRpg.Portal/Controllers/PlotController.cs
- src/JoinRpg.Portal/Views/Plot/EditElementPartial.cshtml
- src/JoinRpg.WebComponents/ButtonPreset.cs
- src/JoinRpg.WebComponents/JoinButton.razor
> Добавить копирование элемента сюжета

- src/JoinRpg.Dal.Impl/Repositories/IdExtensions.cs
- src/JoinRpg.Domain/IdExtensions.cs
- src/JoinRpg.Domain/PlotExtensions.cs
- src/JoinRpg.Portal/Controllers/PlotController.cs
- src/JoinRpg.Portal/Views/Plot/EditElement.cshtml
- src/JoinRpg.Portal/Views/Plot/EditElementPartial.cshtml
- src/JoinRpg.Services.Interfaces/IPlotService.cs
- src/JoinRpg.WebComponents/ElementMoving/JoinMoveControl.razor
- src/JoinRpg.WebPortal.Models/Plot/EditPlotFolderViewModel.cs
- src/JoinRpg.WebPortal.Models/Plot/PlotFolderListViewModel.cs
> Сделано переупорядочивание элементов в сюжете

- src/JoinRpg.Portal/Views/Plot/Edit.cshtml
> Сломан просмотр сюжетов по тегам

- src/JoinRpg.Domain/IdExtensions.cs
- src/JoinRpg.Services.Impl/Projects/CloneProjectHelper.cs
> Не копируются значения выборов в персонаже при копировании проекта

- src/JoinRpg.WebPortal.Models/Plot/PlotFolderListViewModel.cs
> При подсчете количества вводных в сюжеты считаются удаленные

- src/JoinRpg.Dal.Impl/Repositories/HotCharactersRepository.cs
> В панели админа не показывать горячие роли там, где приём заявок закрыт

- src/JoinRpg.Portal/Infrastructure/Authentication/ExternalLoginProfileExtractor.cs
- src/JoinRpg.PrimitiveTypes/AvatarInfo.cs
- src/JoinRpg.Services.Impl/UserServiceImpl.cs
- src/JoinRpg.Services.Interfaces/IUserService.cs
> Баг: показывать телеграм в профиле, даже если нет аватарки

- src/JoinRpg.Portal/Controllers/PlotController.cs
- src/JoinRpg.Portal/Views/Plot/EditElementPartial.cshtml
- src/JoinRpg.WebPortal.Models/Plot/EditPlotFolderViewModel.cs
> Добавить возможность вернуть старую версию вводной

- src/JoinRpg.Portal/Views/Print/Character.cshtml
- src/JoinRpg.Portal/Views/Print/CharacterList.cshtml
- src/JoinRpg.Portal/Views/Print/CharacterListHeader.cshtml
- src/JoinRpg.Portal/Views/Print/PrintCharacter.cshtml
- src/JoinRpg.Portal/wwwroot/css/print.css
> Добавить колонтитул и номер страницы для печати вводной

- src/JoinRpg.Portal/Controllers/Comments/DiscussionRedirectController.cs
> Поправить багу с падением неавторизованных пользователей 

- src/JoinRpg.Portal/Views/Claim/_ClaimAccommodation.cshtml
fixes #3330
Related Work Items: #3330
> Странно отображается поселение с HTML

- src/JoinRpg.Dal.Impl/Repositories/PlotRepositoryImpl.cs
- src/JoinRpg.Data.Interfaces/IPlotRepository.cs
- src/JoinRpg.Portal/Controllers/CharacterListController.cs
- src/JoinRpg.Portal/Views/PlotList/FlatList.cshtml
- src/JoinRpg.WebPortal.Models/Plot/PlotFolderListViewModel.cs
> Показывать только неудаленные сюжеты

- src/JoinRpg.Portal/Controllers/PrintController.cs
> Убрать удаленных персонажей из печати наклеек

- src/JoinRpg.Portal/Controllers/CheckInController.cs
> Поправить редирект после регистрации

- src/JoinRpg.Domain/ClaimCheckInValidator.cs
- src/JoinRpg.Portal/Controllers/XGameApi/CheckInController.cs
- src/JoinRpg.Portal/Views/CheckIn/CheckIn.cshtml
- src/JoinRpg.Portal/Views/Claim/_CheckInStatusBoard.cshtml
- src/JoinRpg.WebPortal.Models/CheckIn/CheckInClaimModel.cs
> Правильнее отображать ошибки полей

- src/JoinRpg.WebPortal.Models/Plot/PlotRenderer.cs
> Не показывать кому привязан сюжет игрокам

- src/JoinRpg.Portal/Controllers/PlotController.cs
- src/JoinRpg.Portal/Views/Plot/Edit.cshtml
- src/JoinRpg.Portal/Views/Plot/EditElementPartial.cshtml
- src/JoinRpg.Portal/Views/PlotList/FlatList.cshtml
- src/JoinRpg.Portal/Views/PlotList/ForGroup.cshtml
- src/JoinRpg.Portal/Views/PlotList/Index.cshtml
- src/JoinRpg.PrimitiveTypes/ProjectMetadata/ProjectInfo.cs
- src/JoinRpg.Web.Plots/IPlotFolderListViewModel.cs
- src/JoinRpg.Web.Plots/PlotElementsView.razor
- src/JoinRpg.Web.Plots/PlotFolderListItemControls.razor
- src/JoinRpg.WebPortal.Models/Plot/EditPlotFolderViewModel.cs
- src/JoinRpg.WebPortal.Models/Plot/PlotFolderListViewModel.cs
> Перевести плоский список в режим редактирования (и исправить #3376)

- src/JoinRpg.Services.Impl/VirtualUsersService.cs
- Исправлен текст ошибки на обобщенный.
- Укорочен код.
> Изменен текст ошибки в сервисе виртуального пользователя

- src/JoinRpg.Domain/Exceptions.cs
- src/JoinRpg.Interfaces/Exceptions.cs
Переместить немного исключений в проект интерфейсов
> Переместить немного исключений в проект интерфейсов

- src/JoinRpg.Portal/Controllers/CharacterListController.cs
- src/JoinRpg.Portal/Controllers/ClaimListController.cs
- src/JoinRpg.Portal/Controllers/Common/ControllerGameBase.cs
- src/JoinRpg.Portal/Controllers/GameGroupsController.cs
- src/JoinRpg.PrimitiveTypes/ProjectMetadata/ProjectInfo.cs
- src/JoinRpg.WebPortal.Models/Characters/CharacterListItemViewModel.cs
Убрать лишний код из контроллеров
> Убрать лишний код из контроллеров

- src/JoinRpg.Domain/CharacterBulkLoader.cs
- src/JoinRpg.Domain/FieldExtensions.cs
- src/JoinRpg.Domain/Problems/CommonProblemFilters/FieldNotSetFilter.cs
- src/JoinRpg.Domain/Problems/CommonProblemFilters/InActiveVariantsFilter.cs
- src/JoinRpg.Domain/Problems/IFieldRelatedProblemFilter.cs
- src/JoinRpg.Domain/Problems/ProblemValidator.cs
> Добавить кеширование родительских групп

- src/JoinRpg.Portal/Views/Claim/Add.cshtml
- src/JoinRpg.WebPortal.Models/Claims/AddClaimViewModel.cs
> Убрать повтор имени
